[project]
name = "langchain-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph",
    "langsmith",
    "langchain-openai",
    "langchain-community",
    "python-dotenv>=1.0.1",
    "streamlit>=1.41.0",
]
